name = "izhimpro-alfacrm-calendar"
main = "src/index.js"
compatibility_date = "2026-06-16"

routes = [
  { pattern = "calendar.izhimpro.ru", custom_domain = true }
]

kv_namespaces = [
  { binding = "CALENDAR_CACHE", id = "4a39d3a78cde44ac81140221eaa88f92", preview_id = "333ddb59b1c94659aa56873efa996d0c" }
]

[triggers]
crons = ["0 * * * *"]

[vars]
ALFACRM_BASE_URL = "https://improizh.s20.online"
ALFACRM_BRANCH_ID = "1"
CALENDAR_DAYS_FORWARD = "180"
CALENDAR_TIMEZONE = "Europe/Samara"
